config/routes.rb
AnnoJr::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :browsers do
    member do
      get 'info'
      get 'genome'
    end
  end
  resources :tracks, except: :show
  resources :views, only: [:create, :destroy]

  root 'static_pages#home'

  match '/tracks/:id', to: "tracks#show", via: [:get, :post]

  match '/about', to: "static_pages#about", via: 'get'
  match '/contact', to: "static_pages#contact", via: 'get'
  match '/help', to: "static_pages#help", via: 'get'
  match '/demo', to: "static_pages#demo", via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @browser = current_user.browsers.build
      @browser_items = current_user.browser_feed
      @track = current_user.tracks.build
      @track_items = current_user.track_feed
    end
  end

  def about
  end

  def help
  end

  def demo
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Anno-JR</h1>

<h3>What is Anno-JR?</h3>
<p>
  Anno-JR is currently just a prototype for collecting sequencing data references and using them to display the data with an Anno-J browser. It is very much a hack at this point which I can hopefully improve a lot in the future.
</p>

<h3>How to use Anno-JR</h3>
<p>
	I have user creation disabled while Anno-JR is in very early testing. Until user creation is opened up, public browsers can be viewed using the "Browsers" link.
</p>

<h3>Development Goals</h3>
<p>
	1. Improve user, track, and browser permission to make public, private, and link-only viewing. Add browser starting configuration options.
</p>
<p>
	2. Create an open source gem that would allow researchers to easily setup servers with APIs for accessing their sequencing data. This would give researchers an easier way to share data with each other and with data browsers.
</p>
<p>
	3. Create my own browser and not rely on Anno-J for presenting sequencing data. When combined with the API gem, accessing and presenting data would be much easier with a new visualization tool.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Mark Urich about Anno-JR at
  <a href="mailto:markurich@gmail.com?Subject=Anno-JR">markurich@gmail.com</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help!?</h1>
<p>
  Having problems? Don't worry, we'll get you fixed up.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row clearfix">
    <%= render 'shared/user_info' %>
    <aside class="span6 feed">
      <%= link_to "Create a new browser!", new_browser_path, class: "btn btn-primary links" %>
      <h3>My Browsers (<%= @browser_items.count %>)</h3>
      <%= render 'shared/feed', object: @browser_items %>
    </aside>
    <aside class="span6 feed">
      <%= link_to "Create a new track!", new_track_path, class: "btn btn-primary links" %>
      <h3>My Tracks (<%= @track_items.count %>)</h3>
      <%= render 'shared/feed', object: @track_items %>
    </aside>
  </div>
<% else %>
	<div class="center hero-unit">
		<h1>Welcome to Anno-JR</h1>
	  <h2>
	    Your resource for building and managing your <a href="http://www.annoj.org">Anno-J</a> instances!
	  </h2>

	  <!-- <%# link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %> -->
	</div>
<% end %>