config/routes.rb
AnnoJr::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :browsers do
    member do
      get 'info'
      get 'genome'
    end
  end
  resources :tracks, except: :show
  resources :views, only: [:create, :destroy]

  root 'static_pages#home'

  match '/tracks/:id', to: "tracks#show", via: [:get, :post]

  match '/about', to: "static_pages#about", via: 'get'
  match '/contact', to: "static_pages#contact", via: 'get'
  match '/help', to: "static_pages#help", via: 'get'
  match '/demo', to: "static_pages#demo", via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

end

app/views/shared/_browser_feed_item.html.erb
<li id="<%= browser_feed_item.id %>">
  <span class="name">
    <%= browser_feed_item.name %>
  </span>
  <span class="links">
  	<%= link_to 'info', info_browser_path(browser_feed_item) %>
  	| <%= link_to 'view', browser_feed_item, target: "_blank" %>
	  <% if current_user?(browser_feed_item.user) %>
	    | <%= link_to 'edit', edit_browser_path(browser_feed_item) %>
	    | <%= link_to "delete", browser_feed_item, method: :delete,
	                                     data: { confirm: "You sure?" },
	                                     title: browser_feed_item.name %>
	  <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if object.any? %>
  <ol class="feedItems">
    <%= render partial: "shared/#{object.first.class.to_s.downcase}_feed_item", collection: object %>
  </ol>
<% end %>

app/views/shared/_track_feed_item.html.erb
<li id="<%= track_feed_item.id %>">
  <span class="name">
    <%= track_feed_item.name %>
  </span>
  <span class="links">
  	<%= link_to 'info', track_feed_item %>
	  <% if current_user?(track_feed_item.user) %>
	    | <%= link_to 'edit', edit_track_path(track_feed_item) %>
	    | <%= link_to "delete", track_feed_item, method: :delete,
	                                     data: { confirm: "You sure?" },
	                                     title: track_feed_item.name %>
	  <% end %>
  </span>
</li>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>